# Base image
FROM python:3.11-slim-bookworm

# Environment
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# Install system dependencies (with BuildKit cache mounts)
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential gcc libpq-dev curl git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Upgrade pip & install dependencies separately
COPY requirements.txt /app/requirements.txt
RUN PIP_NO_CACHE_DIR=0 pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt

# Copy source code
COPY app /app/app

EXPOSE 8000

# Run FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
